name: Build Cross Platform App
permissions:
  contents: write 
on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:

  build-mac:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build Mac App
        run: |
          pyinstaller --windowed --name FileOrganizer ui/app.py

      - name: Zip Mac App
        run: |
          cd dist
          zip -r FileOrganizer-mac.zip FileOrganizer.app

      - name: Upload Mac Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mac-build
          path: dist/FileOrganizer-mac.zip

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build Windows EXE
        run: |
          pyinstaller --onefile --windowed --name FileOrganizer ui/app.py

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: dist/FileOrganizer.exe
  release:
    needs: [build-mac, build-windows]
    runs-on: ubuntu-latest

    steps:
      - name: Download Mac Artifact
        uses: actions/download-artifact@v4
        with:
          name: mac-build

      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            FileOrganizer-mac.zip
            FileOrganizer.exe